### ISSUE TITLE
We want to contribute to translate into Telugu language.

### ISSUE THREAD

**Issue by garutmaangaruda** [nmrih/nmrih-localization-files#10]
I and my brother want to translate the localisation files into Telugu language. Therefore, we are asking for your approval. How do we go by and translate these files? Do we fork? Or is there any other way forward? And, also, any other criteria that we need to fill?

**Comment by felis-catus** [comment]
Unfortunately it appears that Steam doesn't have language support for Telugu, and we're unable to ship localization for it. We have no control over this, so I'm closing the issue. :(

For what it's worth, you can replace nmrih_english.txt in the game files with your changes, and distribute it as a mod.
