### ISSUE TITLE
nmrih_schinese.txt typos

### ISSUE THREAD

**Issue by F1F88** [nmrih/nmrih-localization-files#130]
There is a typo on line 192 of [nmrih_schinese.txt](https://github.com/nmrih/nmrih-localization-files/blob/master/nmrih/resource/nmrih_schinese.txt)

Wrong: "Weapon_me_pickaxe"			"十字稿"
Correct: "Weapon_me_pickaxe"			"十字镐"

difference:
稿: Similar to draft or manuscript
镐: A tool for digging soil

**Comment by Klowby** [comment]
Thank you for pointing it out :3 
Already pulled a request and waiting it to be commited.
Also I am just a community translator so welcome pr with rational reasons when u have spare time for localization :D
