### ISSUE TITLE
Add Steam community translations on repository

### ISSUE THREAD

**Issue by Blueberryy** [nmrih/nmrih-localization-files#16]
Can you add this stuff to repository:
- Steam store page (like short description, full description and other stuff that supports translation on store page)
- Steam achievements file will be great to translate too.
- Steam workshop page (tags too)
- Rich Presence text
- Steam community items (badges, trading cards and profile backgrounds)

**Comment by felis-catus** [comment]
Listed strings are now available in the repo, closing.

**Comment by Blueberryy** [comment]
> Listed strings are now available in the repo, closing.

Good job, Fel
