### ISSUE TITLE
Update the store page?

### ISSUE THREAD

**Issue by Plazehorta** [nmrih/nmrih-localization-files#164]
The store page hasn't been translated in any language yet, as far as I can see. Is it possible to update the page?

**Comment by Blueberryy** [comment]
Also update store page file with new section
![image](https://github.com/nmrih/nmrih-localization-files/assets/36592509/75af44b0-879f-4c27-8e5a-1203009139d4)

**Comment by felis-catus** [comment]
The NMRiH1 maintainer team has no access to the store page, so this may take some time.

**Comment by Blueberryy** [comment]
> The NMRiH1 maintainer team has no access to the store page, so this may take some time.

can you contact them and ask if they can give you special account to do all this? or just give access to your main account. they're busy with second game anyway why they didn't gave you access before?

**Comment by Blueberryy** [comment]
should be added in #187

**Comment by Blueberryy** [comment]
it should be closed i think as we added it recently
