### ISSUE TITLE
Need files for new language translation

### ISSUE THREAD

**Issue by teanteagame** [nmrih/nmrih-localization-files#205]
I want to translate this game into Vietnamese so that my friends who don't know much English can enjoy the game. Can you give me all the needed text files so I can translate them into Vietnamese? I see that Steam supports Vietnamese so it may be easier.

**Comment by Blueberryy** [comment]
> I want to translate this game into Vietnamese so that my friends who don't know much English can enjoy the game. Can you give me all the needed text files so I can translate them into Vietnamese? I see that Steam supports Vietnamese so it may be easier.

You can try to download the game on Steam and then get translation files from there.

**Comment by teanteagame** [comment]
> > I want to translate this game into Vietnamese so that my friends who don't know much English can enjoy the game. Can you give me all the needed text files so I can translate them into Vietnamese? I see that Steam supports Vietnamese so it may be easier.
> 
> You can try to download the game on Steam and then get translation files from there.

Yeah, I have the game installed. I translate some text files but not all the text in the game are translated. I am missing some files somewhere in the game directory so I want to ask if I can have all text files or maybe just all of their directory so I can navigate them.

Besides, the game supports Vietnamese but the font is not quite okay. Is there some way I can contact the dev team to add a custom font for Vietnamese?

**Comment by felis-catus** [comment]
Unfortunately, while Steam has language support for Vietnamese, NMRiH's engine branch Source SDK 2013 doesn't. We have no control over this, so I'm closing the issue.
