### ISSUE TITLE
Text that should be added to translation files

### ISSUE THREAD

**Issue by Blueberryy** [nmrih/nmrih-localization-files#233]
Mouse acceleration setting labels.
![image](https://github.com/user-attachments/assets/d51b5c87-75cd-49c3-97b3-6e834990793d)

"(native)" suffix for resolution setting. (Should be hardcoded but Portal 2 has this translated)
![image](https://github.com/user-attachments/assets/27d5df3a-7fd3-472c-a4d3-67c718b5d460)

Modificator names & descriptions and "NMRiH Team" as official author name.
![image](https://github.com/user-attachments/assets/b65ada9c-c957-4615-a58f-b089924888bc)

Challenge names & descriptions.
![image](https://github.com/user-attachments/assets/8ae697ef-06ef-4459-936b-633dac77e9c7)

Character names & voice names.
![image](https://github.com/user-attachments/assets/b23ae5a7-c38f-4237-aa26-864dc05adb9a)

"CPU Player" for bots on Players Muting menu.
![image](https://github.com/user-attachments/assets/8b54473e-e6c1-429a-a316-60542e639098)

"BOT" tag on scoreboard for bots. (Should be hardcoded but Team Fortress 2 has this translated)
![2024_07_21_0n6_Kleki](https://github.com/user-attachments/assets/470b462b-aa2d-4cce-80c1-ba648376eb74)

**Comment by felis-catus** [comment]
Challenges + Mutators: a4a48a1eea3f8face208e26323641ff954b2a623
Scoreboard BOT: 82807b326b54b8c1882eb1bff9ce0ecada10c1b0

Author names won't be localized, because those are unique nicknames ("NMRiH Team" included).
Mouse acceleration labels, (native) suffix, and player list "CPU Player" can't be localized due to engine restrictions (as mentioned in https://github.com/nmrih/source-game/issues/1312)

Closing as resolved.

**Comment by Blueberryy** [comment]
> Challenges + Mutators: a4a48a1eea3f8face208e26323641ff954b2a623
> Scoreboard BOT: 82807b326b54b8c1882eb1bff9ce0ecada10c1b0
> 
> Author names won't be localized, because those are unique nicknames ("NMRiH Team" included).
> Mouse acceleration labels, (native) suffix, and player list "CPU Player" can't be localized due to engine restrictions (as mentioned in https://github.com/nmrih/source-game/issues/1312)
> 
> Closing as resolved.

What about characters and their voices?

**Comment by Blueberryy** [comment]
@felis-catus ^ sorry for the ping
