### ISSUE TITLE
Add workshop "Add-ons" to repo

### ISSUE THREAD

**Issue by Blueberryy** [nmrih/nmrih-localization-files#77]
it would be awesome if we can translate name of workshop work

**Comment by Blueberryy** [comment]
![steam_FFqOY2n7Ma](https://user-images.githubusercontent.com/36592509/199226137-dd95fc3e-e89a-4c92-8dee-302825108cb0.png)
![steam_t1rGT6ey98](https://user-images.githubusercontent.com/36592509/199226150-a19fa0c0-1dae-4f9b-98e1-0d48ba1a5460.png)
![steam_nQOwslCWyw](https://user-images.githubusercontent.com/36592509/199226155-a93d8251-3cac-4a36-906a-7723506e0b28.png)

**Comment by felis-catus** [comment]
Apparently Steam doesn't support this, it only accepts a raw string.
Will consider removing the "Add-ons" label and reverting back to Steam's default "Items", which appears to be localized.

Closing as "resolved".
